# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rater', '0002_auto_20161005_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='action_genre',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='adventure',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='animation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='children',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comedy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crime',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='documentary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='drama',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fantasy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_noir',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='horror',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='musical',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mystery',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='romance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sci_fi',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thriller',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='war',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='western',
            field=models.BooleanField(),
        ),
    ]
